"""Kotlin code generation for the DisplayBridge protocol (schema.yaml -> Messages.kt)."""
from __future__ import annotations

KT_PRIMITIVE_TYPE = {
    "u8": "Int",
    "u16": "Int",
    "u32": "Long",
    "u64": "Long",
    "varint": "Long",
    "string": "String",
    "bytes": "ByteArray",
}

KT_READ_METHOD = {
    "u8": "io.readU8()",
    "u16": "io.readU16()",
    "u32": "io.readU32()",
    "u64": "io.readU64()",
    "varint": "io.readVarint()",
    "string": "io.readString()",
    "bytes": "io.readBytes()",
}


def pascal(name: str) -> str:
    return name[0].upper() + name[1:]


def kt_field_type(field: dict) -> str:
    t = field["type"]
    if t == "list":
        item = field["item_type"]
        if item == "keyvalue":
            return "List<ConfigEntry>"
        if item == "touch_event":
            return "List<TouchEventItem>"
        return f"List<{KT_PRIMITIVE_TYPE[item]}>"
    return KT_PRIMITIVE_TYPE[t]


def kt_write_stmt(field: dict, accessor: str) -> str:
    t = field["type"]
    if t == "list":
        item = field["item_type"]
        if item == "keyvalue":
            return f"io.writeKeyValueList({accessor})"
        if item == "touch_event":
            return f"io.writeTouchEventList({accessor})"
        writer = {"u8": "io.writeU8(it)", "u16": "io.writeU16(it)", "u32": "io.writeU32(it)", "u64": "io.writeU64(it)"}[item]
        return f"io.writeList({accessor}) {{ {writer} }}"
    if t == "varint":
        return f"io.writeVarint({accessor})"
    if t == "string":
        return f"io.writeString({accessor})"
    if t == "bytes":
        return f"io.writeBytes({accessor})"
    method = {"u8": "writeU8", "u16": "writeU16", "u32": "writeU32", "u64": "writeU64"}[t]
    return f"io.{method}({accessor})"


def kt_read_expr(field: dict) -> str:
    t = field["type"]
    if t == "list":
        item = field["item_type"]
        if item == "keyvalue":
            return "io.readKeyValueList()"
        if item == "touch_event":
            return "io.readTouchEventList()"
        reader = {"u8": "io.readU8()", "u16": "io.readU16()", "u32": "io.readU32()", "u64": "io.readU64()"}[item]
        return f"io.readList {{ {reader} }}"
    return KT_READ_METHOD[t]


def generate_message_class(msg: dict) -> str:
    class_name = f"{msg['name']}Message"
    fields = msg["fields"]
    ctor_params = ",\n    ".join(f"val {f['name']}: {kt_field_type(f)}" for f in fields)
    lines = []
    lines.append(f"data class {class_name}(")
    lines.append(f"    {ctor_params}")
    lines.append(f") : ProtocolMessage {{")
    lines.append(f"    override val type: MessageType get() = MessageType.{msg['name']}")
    lines.append("")
    lines.append("    override fun writePayload(io: WireWriter) {")
    for f in fields:
        lines.append(f"        {kt_write_stmt(f, f['name'])}")
    lines.append("    }")
    lines.append("")
    lines.append("    companion object {")
    lines.append(f"        fun readPayload(io: WireReader): {class_name} {{")
    for f in fields:
        lines.append(f"            val {f['name']} = {kt_read_expr(f)}")
    args = ", ".join(f"{f['name']} = {f['name']}" for f in fields)
    lines.append(f"            return {class_name}({args})")
    lines.append("        }")
    lines.append("")
    lines.append(f"        fun deserialize(bytes: ByteArray): {class_name} = readPayload(WireReader(bytes))")
    lines.append("    }")
    lines.append("")
    lines.append("    fun serialize(): ByteArray = WireWriter().also { writePayload(it) }.toByteArray()")
    lines.append("}")
    return "\n".join(lines)


HEADER = '''// AUTO-GENERATED by tools/protocol-schema/generate.py from schema.yaml.
// DO NOT EDIT BY HAND -- regenerate instead.
@file:Suppress("unused")

package {package}

'''

CONFIG_ENTRY = """data class ConfigEntry(val key: Int, val value: Long) {
    fun serializeInto(io: WireWriter) {
        io.writeU8(key)
        io.writeVarint(value)
    }

    companion object {
        fun readFrom(io: WireReader): ConfigEntry {
            val key = io.readU8()
            val value = io.readVarint()
            return ConfigEntry(key, value)
        }
    }
}"""

def generate_touch_event_item(messages: list[dict]) -> str:
    """TOUCH_BATCH carries a list of the same fields as the TouchEvent
    message, but as a plain struct (no MessageType/wire-type prefix) —
    mirrors the ConfigEntry pattern above."""
    touch_event = next(m for m in messages if m["name"] == "TouchEvent")
    fields = touch_event["fields"]
    ctor_params = ",\n    ".join(f"val {f['name']}: {KT_PRIMITIVE_TYPE[f['type']]}" for f in fields)
    lines = [f"data class TouchEventItem(", f"    {ctor_params}", ") {", "    fun serializeInto(io: WireWriter) {"]
    for f in fields:
        lines.append(f"        {kt_write_stmt(f, f['name'])}")
    lines.append("    }")
    lines.append("")
    lines.append("    companion object {")
    lines.append("        fun readFrom(io: WireReader): TouchEventItem {")
    for f in fields:
        lines.append(f"            val {f['name']} = {kt_read_expr(f)}")
    args = ", ".join(f"{f['name']} = {f['name']}" for f in fields)
    lines.append(f"            return TouchEventItem({args})")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines)


VIDEO_FRAME_HEADER = """data class VideoFrameHeader(val len: Long, val flags: Int, val ptsUs: Long) {
    fun serialize(): ByteArray {
        val io = WireWriter()
        io.writeU32(len)
        io.writeU8(flags)
        io.writeU64(ptsUs)
        return io.toByteArray()
    }

    companion object {
        const val WIRE_SIZE = 4 + 1 + 8

        fun deserialize(bytes: ByteArray): VideoFrameHeader {
            val io = WireReader(bytes)
            val len = io.readU32()
            val flags = io.readU8()
            val ptsUs = io.readU64()
            return VideoFrameHeader(len, flags, ptsUs)
        }
    }
}"""

WIRE_IO = """class WireWriter {
    private val buffer = java.io.ByteArrayOutputStream()

    fun writeU8(value: Int) { buffer.write(value and 0xFF) }

    fun writeU16(value: Int) {
        buffer.write(value and 0xFF)
        buffer.write((value ushr 8) and 0xFF)
    }

    fun writeU32(value: Long) {
        for (i in 0 until 4) buffer.write(((value ushr (i * 8)) and 0xFF).toInt())
    }

    fun writeU64(value: Long) {
        for (i in 0 until 8) buffer.write(((value ushr (i * 8)) and 0xFF).toInt())
    }

    fun writeVarint(value: Long) {
        var v = value
        while (v and 0x7F.inv().toLong() != 0L) {
            buffer.write(((v and 0x7F) or 0x80).toInt())
            v = v ushr 7
        }
        buffer.write(v.toInt())
    }

    fun writeString(value: String) {
        val bytes = value.toByteArray(Charsets.UTF_8)
        writeU16(bytes.size)
        buffer.write(bytes)
    }

    fun writeBytes(value: ByteArray) {
        writeU16(value.size)
        buffer.write(value)
    }

    fun <T> writeList(items: List<T>, writeItem: (T) -> Unit) {
        writeU16(items.size)
        for (item in items) writeItem(item)
    }

    fun writeKeyValueList(items: List<ConfigEntry>) {
        writeU16(items.size)
        for (item in items) item.serializeInto(this)
    }

    fun writeTouchEventList(items: List<TouchEventItem>) {
        writeU16(items.size)
        for (item in items) item.serializeInto(this)
    }

    fun toByteArray(): ByteArray = buffer.toByteArray()
}

class WireReader(private val bytes: ByteArray) {
    private var pos = 0

    fun readU8(): Int = bytes[pos++].toInt() and 0xFF

    fun readU16(): Int {
        val b0 = readU8()
        val b1 = readU8()
        return b0 or (b1 shl 8)
    }

    fun readU32(): Long {
        var result = 0L
        for (i in 0 until 4) result = result or (readU8().toLong() shl (i * 8))
        return result
    }

    fun readU64(): Long {
        var result = 0L
        for (i in 0 until 8) result = result or (readU8().toLong() shl (i * 8))
        return result
    }

    fun readVarint(): Long {
        var result = 0L
        var shift = 0
        while (true) {
            val b = readU8()
            result = result or ((b.toLong() and 0x7F) shl shift)
            if (b and 0x80 == 0) break
            shift += 7
        }
        return result
    }

    fun readString(): String {
        val length = readU16()
        val slice = bytes.copyOfRange(pos, pos + length)
        pos += length
        return String(slice, Charsets.UTF_8)
    }

    fun readBytes(): ByteArray {
        val length = readU16()
        val slice = bytes.copyOfRange(pos, pos + length)
        pos += length
        return slice
    }

    fun <T> readList(readItem: () -> T): List<T> {
        val count = readU16()
        return List(count) { readItem() }
    }

    fun readKeyValueList(): List<ConfigEntry> {
        val count = readU16()
        return List(count) { ConfigEntry.readFrom(this) }
    }

    fun readTouchEventList(): List<TouchEventItem> {
        val count = readU16()
        return List(count) { TouchEventItem.readFrom(this) }
    }
}
"""

FRAMING = """object MessageFraming {
    fun writeFramed(message: ProtocolMessage): ByteArray {
        val payloadWriter = WireWriter()
        message.writePayload(payloadWriter)
        val payload = payloadWriter.toByteArray()
        val envelope = WireWriter()
        envelope.writeU8(message.type.value)
        envelope.writeU16(payload.size)
        val out = java.io.ByteArrayOutputStream()
        out.write(envelope.toByteArray())
        out.write(payload)
        return out.toByteArray()
    }

    fun readFramed(bytes: ByteArray): ProtocolMessage {
        val header = WireReader(bytes)
        val typeByte = header.readU8()
        val length = header.readU16()
        val type = MessageType.fromByte(typeByte)
            ?: throw IllegalArgumentException("Unknown MessageType: $typeByte")
        val payload = bytes.copyOfRange(3, 3 + length)
        val io = WireReader(payload)
        return when (type) {
{FRAMING_CASES}
        }
    }
}"""


def generate_kotlin_files(schema: dict) -> dict[str, str]:
    """Returns {relative_filename: file_contents} for the protocol/generated/ folder."""
    package = schema["meta"]["package_kotlin"]
    message_types = schema["message_types"]
    messages = schema["messages"]

    # Enum member names must match the PascalCase message name used everywhere
    # else (message-class `type` getter, framing `when`: `MessageType.{msg['name']}`),
    # NOT the raw SCREAMING_CASE schema key — otherwise the generated code does
    # not compile (enum `CAPS` vs reference `MessageType.Caps`).
    type_key_to_name = {m["type"]: m["name"] for m in messages}
    enum_entries = ",\n    ".join(
        f"{type_key_to_name[name]}(0x{value:02X})" for name, value in message_types.items()
    )
    enum_block = f"""enum class MessageType(val value: Int) {{
    {enum_entries};

    companion object {{
        fun fromByte(value: Int): MessageType? = entries.firstOrNull {{ it.value == value }}
    }}
}}"""

    # Handshake messages (type < 0x10, e.g. CAPS/CONFIG) live in their own file,
    # separate from the steady-state control-loop messages (type >= 0x10) —
    # keeps every generated file comfortably under ~200 lines.
    handshake_messages = [m for m in messages if schema["message_types"][m["type"]] < 0x10]
    loop_messages = [m for m in messages if schema["message_types"][m["type"]] >= 0x10]

    messages_kt = (
        HEADER.format(package=package)
        + "interface ProtocolMessage {\n    val type: MessageType\n    fun writePayload(io: WireWriter)\n}\n\n"
        + enum_block
        + "\n"
    )

    handshake_messages_kt = (
        HEADER.format(package=package)
        + "\n\n".join(generate_message_class(m) for m in handshake_messages)
        + "\n"
    )

    control_messages_kt = (
        HEADER.format(package=package)
        + "\n\n".join(generate_message_class(m) for m in loop_messages)
        + "\n"
    )

    protocol_common_kt = (
        HEADER.format(package=package)
        + CONFIG_ENTRY
        + "\n\n"
        + generate_touch_event_item(messages)
        + "\n\n"
        + VIDEO_FRAME_HEADER
        + "\n"
    )

    wire_io_kt = HEADER.format(package=package) + WIRE_IO

    framing_cases = "\n".join(
        f"            MessageType.{m['name']} -> {m['name']}Message.readPayload(io)"
        for m in messages
    )
    framing = FRAMING.replace("{FRAMING_CASES}", framing_cases)
    message_framing_kt = HEADER.format(package=package) + framing + "\n"

    return {
        "Messages.kt": messages_kt,
        "HandshakeMessages.kt": handshake_messages_kt,
        "ControlMessages.kt": control_messages_kt,
        "ProtocolCommon.kt": protocol_common_kt,
        "WireIO.kt": wire_io_kt,
        "MessageFraming.kt": message_framing_kt,
    }
